const express=require('express');const {db}=require('../db/database');const {posUsers}=require('../middleware/auth');const router=express.Router();router.use(posUsers);
const map=o=>{const items=db.prepare('SELECT * FROM open_order_items WHERE open_order_id=? ORDER BY id').all(o.id),subtotal=items.reduce((s,x)=>s+x.quantity*x.unit_price,0);return{...o,items,subtotal,total:Math.max(0,subtotal-o.discount)};};
function validate(b){if(!String(b.customer_name||'').trim())return'Customer name is required';if(!Array.isArray(b.items)||!b.items.length)return'At least one item is required';for(const x of b.items){const q=Number(x.quantity),p=Number(x.unit_price);if(!Number.isFinite(q)||q<=0||!Number.isFinite(p)||p<0)return'Invalid item';if(x.type==='gaming'&&p!==100000)return'Gaming price cannot be changed';}return null;}
function save(id,items){const ins=db.prepare('INSERT INTO open_order_items(open_order_id,product_id,name,type,quantity,unit_price) VALUES(?,?,?,?,?,?)');for(const x of items)ins.run(id,x.product_id||null,x.name,x.type==='gaming'?'gaming':'product',x.quantity,x.type==='gaming'?100000:x.unit_price);}
router.get('/',(_req,res)=>res.json(db.prepare('SELECT * FROM open_orders ORDER BY updated_at DESC,id DESC').all().map(map)));
router.get('/:id',(req,res)=>{const o=db.prepare('SELECT * FROM open_orders WHERE id=?').get(req.params.id);if(!o)return res.status(404).json({error:'Not found'});res.json(map(o));});
router.post('/',(req,res)=>{const e=validate(req.body);if(e)return res.status(400).json({error:e});const b=req.body,id=db.transaction(()=>{const id=db.prepare(`INSERT INTO open_orders(customer_name,discount,notes,created_by,created_by_name,gaming_players,order_type) VALUES(?,?,?,?,?,?,?)`).run(b.customer_name.trim(),Number(b.discount)||0,b.notes||null,req.session.userId,req.session.username,Number(b.gaming_players)||0,b.order_type==='gaming'?'gaming':'product').lastInsertRowid;save(id,b.items);return id;})();res.json({id});});
router.put('/:id',(req,res)=>{const e=validate(req.body);if(e)return res.status(400).json({error:e});const b=req.body;db.transaction(()=>{db.prepare(`UPDATE open_orders SET customer_name=?,discount=?,notes=?,gaming_players=?,order_type=?,updated_at=datetime('now') WHERE id=?`).run(b.customer_name.trim(),Number(b.discount)||0,b.notes||null,Number(b.gaming_players)||0,b.order_type==='gaming'?'gaming':'product',req.params.id);db.prepare('DELETE FROM open_order_items WHERE open_order_id=?').run(req.params.id);save(req.params.id,b.items);})();res.json({ok:true});});
router.delete('/:id',(req,res)=>{db.prepare('DELETE FROM open_orders WHERE id=?').run(req.params.id);res.json({ok:true});});module.exports=router;
