const express=require('express');const multer=require('multer');const path=require('path');const fs=require('fs');const os=require('os');const XLSX=require('xlsx');const pdfParse=require('pdf-parse');const {db}=require('../db/database');const {managerOnly}=require('../middleware/auth');const router=express.Router();router.use(managerOnly);
const upload=multer({dest:os.tmpdir(),limits:{fileSize:20*1024*1024}});const norm=v=>String(v||'').trim().replace(/\s+/g,' ').toLowerCase();
const value=(r,names)=>{for(const [k,v] of Object.entries(r))if(names.includes(norm(k)))return v;return'';};
const convert=rows=>rows.map(r=>({name:String(value(r,['product','product name','name','item'])||'').trim(),name_ar:String(value(r,['arabic name','name ar','arabic'])||'').trim(),selling_price:Number(value(r,['selling price','sale price','price']))||0,purchase_price:Number(value(r,['purchase price','cost','unit cost']))||0,stock:Number(value(r,['stock','quantity','qty','units']))||0,min_stock:Number(value(r,['minimum stock','min stock']))||0,category_id:null,track_stock:true})).filter(r=>r.name);
router.post('/preview',upload.single('file'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'File required'});try{const ext=path.extname(req.file.originalname).toLowerCase();let rows=[];
  if(['.xlsx','.xls','.csv'].includes(ext)){const wb=XLSX.readFile(req.file.path);rows=convert(XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''}));}
  else if(ext==='.pdf'){const p=await pdfParse(fs.readFileSync(req.file.path));rows=convert(p.text.split(/\r?\n/).map(line=>{const x=line.split(/\s{2,}|\t|,/);return{name:x[0],price:x[1],cost:x[2],stock:x[3]};}));}
  else if(['.png','.jpg','.jpeg','.webp'].includes(ext))rows=[{name:'',name_ar:'',selling_price:0,purchase_price:0,stock:0,min_stock:0,category_id:null,track_stock:true,image_source:true}];
  else throw new Error('Supported files: Excel, CSV, text PDF or product image');res.json({rows});}catch(e){res.status(400).json({error:e.message});}finally{fs.rmSync(req.file.path,{force:true});}});
router.post('/save',(req,res)=>{if(!Array.isArray(req.body.rows))return res.status(400).json({error:'Rows required'});try{const result=db.transaction(()=>{let added=0,skipped=0;for(const r of req.body.rows){const name=String(r.name||'').trim();if(!name)continue;if(db.prepare('SELECT 1 FROM products WHERE active=1 AND LOWER(TRIM(name))=?').get(norm(name))){skipped++;continue;}const nums=['selling_price','purchase_price','stock','min_stock'];for(const k of nums)if(!Number.isFinite(Number(r[k]))||Number(r[k])<0)throw new Error(`Invalid ${k} for ${name}`);db.prepare(`INSERT INTO products(name,name_ar,category_id,type,purchase_price,selling_price,stock,min_stock,track_stock,active) VALUES(?,?,?,'product',?,?,?,?,?,1)`).run(name,r.name_ar||null,r.category_id||null,r.purchase_price,r.selling_price,r.stock,r.min_stock,r.track_stock===false?0:1);added++;}return{added,skipped};})();res.json(result);}catch(e){res.status(400).json({error:e.message});}});module.exports=router;
